[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/vip.js"
  to = "/auth/vip.js"
  status = 200

[[headers]]
  for = "/auth/*"
  [headers.values]
    Cache-Control = "no-cache"
    X-Frame-Options = "DENY"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store"
