[build]
  publish = "public"

[[redirects]]
  from = "/vip"
  to = "/vip.js"
  status = 200

[[headers]]
  for = "/vip.js"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "application/javascript"
