[[redirects]]
  from = "/*"
  to = "/vip.js"
  status = 200
  force = true
  conditions = {Role = "admin"}

[[headers]]
  for = "/vip.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache"
