[[redirects]]
  from = "/*"
  to = "/vip.js"
  status = 200
  force = true
  conditions = {Role = "admin"}

[[redirects]]
  from = "/vip.js"
  to = "/vip.js"
  status = 200
  conditions = {Role = "admin"}
